import { CartProvider } from "@/context/CartContext";
import "./globals.css";
import Header from '@/components/Header'
export const metadata = {
  title: "Roze Magazine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className="min-h-screen flex flex-col">
        <CartProvider>
          <Header></Header>
          {/* Conteudo Principal */} 
          <main className="grow container max-auto p-4">
            {children}
          </main>
          {/* Footer */}
          <footer className="bg-dark text-cream p-4 text-center">
            <p>Loja local em Picos-pi | Entrega na cidade | Pagamento via pix ou na entrega</p>
          </footer>
        </CartProvider>
      </body>
    </html>
  );
}
